### ISSUE TITLE
Fail when node has prefix

### ISSUE THREAD

**Issue by SergioFloresG** [spatie/array-to-xml#60]
Hello.

An error is presented when generating an xml when the name of the node has a prefix

```php
protected function addCollectionNode(DOMElement $element, $value)
{
    // $element: { tagName => "fx:Mercancia" }
    // $value: { _attributes => [6] } [1]
    if ($element->childNodes->length === 0 && $element->attributes->length === 0) {
        $this->convertElement($element, $value);
        return;
    }

    // When create a new child, FAILS!
    $child = new DOMElement($element->tagName);
    $element->parentNode->appendChild($child);
    $this->convertElement($child, $value);
}
```
Trace
```
 /home/cpavs/api-facturacion/vendor/spatie/array-to-xml/src/ArrayToXml.php(159): DOMElement->__construct('fx:Mercancia') 
#1 /home/cpavs/api-facturacion/vendor/spatie/array-to-xml/src/ArrayToXml.php(118): Spatie\ArrayToXml\ArrayToXml->addCollectionNode(Object(DOMElement), Array) 
#2 /home/cpavs/api-facturacion/vendor/spatie/array-to-xml/src/ArrayToXml.php(140): Spatie\ArrayToXml\ArrayToXml->convertElement(Object(DOMElement), Array) 
#3 /home/cpavs/api-facturacion/vendor/spatie/array-to-xml/src/ArrayToXml.php(115): Spatie\ArrayToXml\ArrayToXml->addNode(Object(DOMElement), 'fx:Mercancia', Array) 
#4 /home/cpavs/api-facturacion/vendor/spatie/array-to-xml/src/ArrayToXml.php(140): Spatie\ArrayToXml\ArrayToXml->convertElement(Object(DOMElement), Array) 
#5 /home/cpavs/api-facturacion/vendor/spatie/array-to-xml/src/ArrayToXml.php(115): Spatie\ArrayToXml\ArrayToXml->addNode(Object(DOMElement), 'fx:Mercancias', Array) 
#6 /home/cpavs/api-facturacion/vendor/spatie/array-to-xml/src/ArrayToXml.php(140): Spatie\ArrayToXml\ArrayToXml->convertElement(Object(DOMElement), Array) 
#7 /home/cpavs/api-facturacion/vendor/spatie/array-to-xml/src/ArrayToXml.php(115): Spatie\ArrayToXml\ArrayToXml->addNode(Object(DOMElement), 'fx:ComercioExte...', Array) 
#8 /home/cpavs/api-facturacion/vendor/spatie/array-to-xml/src/ArrayToXml.php(140): Spatie\ArrayToXml\ArrayToXml->convertElement(Object(DOMElement), Array) 
#9 /home/cpavs/api-facturacion/vendor/spatie/array-to-xml/src/ArrayToXml.php(115): Spatie\ArrayToXml\ArrayToXml->addNode(Object(DOMElement), 'fx:Complementos', Array) 
#10 /home/cpavs/api-facturacion/vendor/spatie/array-to-xml/src/ArrayToXml.php(49): Spatie\ArrayToXml\ArrayToXml->convertElement(Object(DOMElement), Array) 
#11 /home/cpavs/api-facturacion/app/Empresa/Levis/Proceso/LeviComercioExterior.php(53): Spatie\ArrayToXml\ArrayToXml->__construct(Array, Array, true, 'UTF-8') 
```

The original array data.

```
array (
  'fx:Complementos' => 
  array (
    'fx:ComercioExterior11' => 
    array (
      '_attributes' => 
      array (
        'Version' => '1.1',
        'TipoOperacion' => '2',
        'ClaveDePedimento' => 'A1',
        'CertificadoOrigen' => '0',
        'Subdivision' => '0',
        'TipoCambioUSD' => '18.80',
        'Incoterm' => 'EXW',
        'TotalUSD' => '3112.00',
      ),
      'fx:Emisor' => 
      array (
        'fx:Domicilio' => 
        array (
          '_attributes' => 
          array (
            'Calle' => 'AV. TEJOCOTES',
            'Localidad' => '04',
            'Municipio' => '121',
            'Estado' => 'MEX',
            'Pais' => 'MEX',
            'CodigoPostal' => '54763',
          ),
        ),
      ),
      'fx:Receptor' => 
      array (
        'fx:Domicilio' => 
        array (
          '_attributes' => 
          array (
            'Calle' => 'MANZANA 50, AVENIDA 6 CON CALLE 4 LOCAL 5',
            'Estado' => 'A',
            'Pais' => 'PAN',
            'CodigoPostal' => '00234',
          ),
        ),
      ),
      'fx:Mercancias' => 
      array (
        'fx:Mercancia' => 
        array (
          0 => 
          array (
            '_attributes' => 
            array (
              'NoIdentificacion' => '342680030',
              'CantidadAduana' => '32',
              'UnidadAduana' => '06',
              'FraccionArancelaria' => '62034294',
              'ValorUnitarioAduana' => '22.00',
              'ValorDolares' => '704.00',
            ),
          ),
          1 => 
          array (
            '_attributes' => 
            array (
              'NoIdentificacion' => '005051595',
              'CantidadAduana' => '36',
              'UnidadAduana' => '06',
              'FraccionArancelaria' => '62034294',
              'ValorUnitarioAduana' => '18.00',
              'ValorDolares' => '648.00',
            ),
          ),
          2 => 
          array (
            '_attributes' => 
            array (
              'NoIdentificacion' => '005012613',
              'CantidadAduana' => '80',
              'UnidadAduana' => '06',
              'FraccionArancelaria' => '62034294',
              'ValorUnitarioAduana' => '22.00',
              'ValorDolares' => '1760.00',
            ),
          ),
        ),
      ),
    ),
  ),
)
```

**Comment by freekmurze** [comment]
Feel free to PR a fix. Make sure to include tests.

**Comment by SergioFloresG** [comment]
Currently, space names can be registered correctly when they are individual nodes and when they are composed of several nodes (array) with the same label and name.

### Individual tags
```php
$data = [
    'f:table' => [
       'f:tr' => [
           'f:name'   => 'African Coffee Table',
           'f:width'  => '80',
           'f:length' => 120
        ]
    ]
];

$root = [
    '_attributes' => [
        'xmlns:f' => 'https://www.w3schools.com/furniture'
    ]
];
```

### Multiple tags
```php
$data = [
    'h:table' => [
        'h:tr' => [
            ['h:td' => ['Apples', 'Bannanas']],
            ['h:td' => ['Orange', 'Kiwi']]
        ]
    ]
];

$root = [
    '_attributes' => [
        'xmlns:h' => 'http://www.w3.org/TR/html4/'
    ]
]
```

I try to generate a new branch but when make the push i receibe 404 error.
